export const MOCK_COMMENTS = [
  {
    id: 1,
    avatarColor: 'var(--primary)',
    avatarLetter: 'F',
    username: 'ForestDweller',
    timeAgo: '3 hours ago',
    text: 'The hand-drawn art is absolutely magical 🍄 Every location feels like a page from a children’s storybook. The mushroom village made me cry happy tears!',
    likes: 12,
    liked: false,
  },
  {
    id: 2,
    avatarColor: 'var(--primary)',
    avatarLetter: 'H',
    username: 'HerbalTeaLover',
    timeAgo: '1 day ago',
    text: 'Perfect cozy evening game — brew a cup of chamomile, wrap in a blanket and help the little Tukoni prepare for winter. The puzzles are gentle but satisfying.',
    likes: 5,
    liked: false,
  },
  {
    id: 3,
    avatarColor: 'var(--primary)',
    avatarLetter: 'C',
    username: 'CottageCoreMia',
    timeAgo: '3 days ago',
    text: 'I want to live inside this game forever 🌿 The NPCs are so charming, the tea recipes are real, and the atmosphere is pure warmth and calm.',
    likes: 8,
    liked: true,
  },
  {
    id: 4,
    avatarColor: 'var(--white)',
    avatarLetter: 'S',
    username: 'SoftPetals',
    timeAgo: '5 days ago',
    text: 'Such a wholesome vibe! The color palette is soothing, and the tiny details in every scene make exploring a joy.',
    likes: 3,
    liked: false,
  },
];
